### ISSUE TITLE
FlexLayout missing setWrapMode api

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-ordered-layout-flow#10]
@haiwan commented on [Mon Nov 13 2017](https://github.com/vaadin/flow/issues/2906)

FlexLayout currently doesn't have API for setting wrap mode, in order to change the wrap, I have to deal with css in Java. Even though the code is quite simple, it's still something that Java-centered developers might not be familiar with. Getting the API as an auto complete suggestion in the IDE also beats any "manual" approach.

**Comment by appreciated** [comment]
Also it is missing the `flex-direction` if I'm not mistaken?

**Comment by appreciated** [comment]
@pleku would you mind me adding a `setFlexDirection` method to #76?

**Comment by pleku** [comment]
@appreciated you can make another PR please. But please wait until we have refactored the project and merged the PR that does that (we are doing it now within the next two hours).

**Comment by appreciated** [comment]
@pleku Sure will do!
