### ISSUE TITLE
The demos at vaadin.com have broken buttons (that don't look like buttons)

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-ordered-layout-flow#100]
See https://vaadin.com/components/vaadin-ordered-layout/java-examples/verticallayout

**Comment by web-padawan** [comment]
Fixed at https://vaadin.com by adding following styles for `<button>` in Java demos:

![Screenshot 2020-02-18 at 12 51 26](https://user-images.githubusercontent.com/10589913/74729656-75c49b80-524d-11ea-9f23-4c9370921c89.png)
