### ISSUE TITLE
Change the scrollable API to a separate scrollable container

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-ordered-layout-flow#108]
New scrollable container that can display scrollbars when its content is overflowing and can be used in existing layouts. 
Verify that button and other vaadin components look as expected inside the container.
Related to #28 https://github.com/vaadin/vaadin-core/issues/217
Requires reverting #104

**Comment by heruan** [comment]
Hope this will happen for [`vaadin-grid`](https://github.com/vaadin/vaadin-grid/issues/1364) before 😄

**Comment by alvarezguille** [comment]
ScrollContainer added in #116 
Targeted versions:
* vaadin-ordered-layout-flow 2.1 in Vaadin 14.2
* vaadin-ordered-layout-flow 3.1 in Vaadin 16
