### ISSUE TITLE
Removing scroller contents via scroller.setContents(null) throws NPE

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-ordered-layout-flow#126]
Removing scroller contents via scroller.setContents(null) throws NPE. It should be possible to "revert" the scroller to the original state with no contents by calling scroller.setContents(null).

Workaround is to remove all children via `getElement().removeAllChildren()`.

**Comment by mvysny** [comment]
Alternatively, make scroller a `HasComponents` and allow multiple children.

**Comment by web-padawan** [comment]
Fixed by #133
