### ISSUE TITLE
Rename setWrapMode to setFlexWrap

### ISSUE THREAD

**Issue by eriklumme** [vaadin/vaadin-ordered-layout-flow#127]
The properties `flex-grow`, `flex-shrink`, `flex-direction`, and `flex-basis` all have `flex` prefixes in the corresponding Flow methods, e.g. `setFlexGrow`.

`flex-wrap`, however, does not, as the method is called `setWrapMode`.

This is confusing, as the method does not appear as a suggestion in an IDE when typing `setFlex...`.

**Comment by tomivirkki** [comment]
Deprecate the wrap-mode API and add flex-wrap
