### ISSUE TITLE
SpacingMode is undocumented

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-ordered-layout-flow#26]
@tmattsso commented on [Wed Sep 20 2017](https://github.com/vaadin/flow/issues/2447)

The API gives no hints on why AROUND is different to BETWEEN, or what EVENLY means.

---

@pleku commented on [Wed Sep 20 2017](https://github.com/vaadin/flow/issues/2447#issuecomment-330820860)

It seems that both enums, `Alignment` and `JustifyContentMode` are missing all javadocs for the enum values.

**Comment by heruan** [comment]
I've documented the enums and added the missing value in https://github.com/vaadin/vaadin-ordered-layout-flow/pull/19. I can split the changes in a different PR, if needed.

**Comment by heruan** [comment]
#19 is merged and it adds JavaDocs to the enums, I guess this can be closed.

**Comment by denis-anisimov** [comment]
Looks like it's done.
`Alignment` and `JustifyContentMode` are documented and there is no `SpacingMode` anymore.
