### ISSUE TITLE
add convenience API for enabling scrolling in FlexLayout

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-ordered-layout-flow#28]
@tmattsso commented on [Wed Dec 20 2017](https://github.com/vaadin/flow/issues/3194)

with the removal of Panel, V10 is missing a Java API to enable scrolling for any layout. Please to add.

**Comment by Legioth** [comment]
Does this only apply for `VerticalLayout` and `HorizontalLayout`, or would similar API also be good to have for e.g. `Div`?

**Comment by Haprog** [comment]
Seems like we might need a similar convenience API also in the web components (context: https://vaadin.slack.com/archives/CHPCTB0BY/p1567510420001500). In that case it would be good to add it first to the web components and then use that in a Java API.

**Comment by alvarezguille** [comment]
Adding scrollable API to existing layouts could result in unexpected shrinking behavior in other components. A separate ScrollContainer component was created instead, added in #116 
Targeted versions:
* vaadin-ordered-layout-flow 2.1 in Vaadin 14.2
* vaadin-ordered-layout-flow 3.1 in Vaadin 16
