### ISSUE TITLE
Add Spacing API to Horizontal- and VerticalLayout

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-ordered-layout-flow#34]
Split out from #1.

There are the following options for the `theme` attribute in Lumo theme:
- spacing-xs
- spacing-s
- spacing (medium/default)
- spacing-l
- spacing-xl

Suggested API takes the simplicity route by just adding one method for `HorizontalLayout` and `VerticalLayout`:
```java
void setSpacing(boolean spacing);
```
This method triggers the `theme='spacing'` to be applied.
If the users want to use the other variant, they should instead use the `ThemeList` `layout.getThemeList().add("spacing-m");` added in #1.
The different variants **could** be added as constants, but that is something the we preferably should create automatically for each component using our component generator. Thus it is not a part of this issue to add those.

### Acceptance Criteria
- There is a demo for triggering spacing on
- There is a demo for showing the variants of the spacing using the `ThemeList` API.

**Comment by pleku** [comment]
One thing to note here, that the defaults won't stay the same from FW 8 since there `HorizontalLayout` has `spacing` on by default. But for Vaadin 10 it is more difficult since `spacing` might not have any effect, it depends on the theme used.

The question IMO is now between which do we prioritize:
a) the first time and most user convenience of having the default there
  - they use our themes and will, as our experience has showed, appreciate the spacing to be there
b) the users who have their own theming and for them the default of spacing is unnecessary

I would go for a) over b) since the b) is a much smaller use audience, and I would expect it to have less impact to have have 1/100 to remove the default spacing than add it for most of the time.

**Comment by Legioth** [comment]
> The question IMO is now between which do we prioritize

I'm also preferring a), i.e. making things work nicely out of the box even if that might cause some small confusion in advanced cases with completely custom theme.s

**Comment by SomeoneToIgnore** [comment]
Have added a PR.

One thing to discuss here is the fact that now a component may have multiple `spacing-*` themes on it with this api (see updated demo in the PR).

**Comment by pleku** [comment]
>One thing to discuss here is the fact that now a component may have multiple spacing-* themes on it with this api (see updated demo in the PR).

If you add many variants, then sure you have many variants. At least it is not easy and it would be close to impossible to always be able to prevent that from happening since we cannot know which variants can be conflicting.
