### ISSUE TITLE
HorizontalLayout and FlexComponent.JustifyContentMode.BETWEEN yields unexpected results

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-ordered-layout-flow#54]
My use case is to have two child `h3` and `h4` in a `HorizontalLayout`, showing a "Welcome" text justified to the left, "App Name" justified to the right. In hopes to achieve that, I have set h3 and h4 to wrap its contents and set the parent `HorizontalLayout` to "Between", hoping for the `HorizontalLayout` to add space between those two items, pushing them apart.

However, there is a third item: an invisible `::before` which is also considered by the flex layout engine, and hence the flex layout engine distributes space between the `::before` and `h3`.

Please see the screenshot attached. Could it be possible to remove the `::before` from `HorizontalLayout`?

![screenshot from 2018-04-20 18-33-38](https://user-images.githubusercontent.com/254091/39060583-70e00272-44ca-11e8-9715-54b1bc6331a6.png)

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-ordered-layout #49](https://github.com/vaadin/vaadin-ordered-layout/issues/49) via [**ZenHub**](https://www.zenhub.com/)
