### ISSUE TITLE
FlexLayout is missing some properties

### ISSUE THREAD

**Issue by appreciated** [vaadin/vaadin-ordered-layout-flow#80]
As a user when using the FlexLayout I want to have access to the whole flexbox API.
Currently missing:
- flex-shrink
- order
- flex-direction
- align-content
- flex-basis

**Comment by marcushellberg** [comment]
I would also add the  `flex` convenience property

**Comment by svipal** [comment]
Hey I'm working on this and I noticed flex-basis, flex-shrink and flex-grow can take 'inherit' or 'initial' values in addition to numbers. 
What's the consensus in the project, do you prefer setting the attributes with an int anyway for type safety like the colspan in vaadin-form-layout flow, or should we accept strings and verify they are valid values ? (or make a custom enum..)

**Comment by svipal** [comment]
Hey, I was looking in the wrong place (FlexLayout), saw the setFlexGrow function in FlexComponent, will follow that convention unless the above raised points still stand.

**Comment by svipal** [comment]
@pleku, @appreciated  or anyone that knows about this :
hey, sorry for the delay. 
I thought this would be closed in a week but there's something I don't actually understand: where are the FlexConstants used / referenced ? Looked in vaadin-ordered-layout and it's not there.
Just adding 'flexBasis', 'flexDirection', etc to them and setting the methods appropriately (kind of like this commit : https://github.com/vaadin/vaadin-ordered-layout-flow/commit/cb1922f9a86f13637c33fd77aee6b25cbe152fdb but with the methods in the FlexComponent class ) doesn't actually work when I test it.

**Comment by pleku** [comment]
Thanks for @sahalsaad for the contribution and patience.

This feature ought to land to Vaadin 14.1, starting from the next prerelease (mayhaps next week).

**Comment by MojoManagement** [comment]
When can we expect this feature?

**Comment by pleku** [comment]
@MojoManagement unfortunately this was postponed to 14.2, which I would guess is released early 2020.
