### ISSUE TITLE
setSizeFull() confusing to Vaadin 8 users

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-ordered-layout-flow#86]
I have a root VerticalLayout() with setSizeFull() (so that it would fill in the viewport); I then add a button and a grid. I want the grid to fill the remaining space of the VerticalLayout. Since there's VerticalLayout and setSizeFull(), Vaadin 8 user would expect the following code to work properly:

```
final Grid<Foo> grid = new Grid<>();
vl.addComponent(grid);
vl.setFlexGrow(1d, grid);
grid.setSizeFull();
```

(that is, I, as a Vaadin 8 user, expect the Grid to fill in the slot allocated to it by the parent Vertical Layout).

Of course, with Vaadin 10 there are no slots, VerticalLayout is just a flex layout and the Grid will match the height of the parent layout, thus scrolling outside of the viewport (since there's also the Button). If a person knows this, it is to be expected.

However, for Vaadin 8 person this is extremely confusing. I do not know how to solve this, but the current solution is confusing.

We could introduce slots to VerticalLayout; or we could rename the setSizeFull() (since it will do something else than the Vaadin 8 user expects anyway, for all components); or there could be at least a big warning (which may go unnoticed).

**Comment by pleku** [comment]
### Acceptance Criteria
- add `addAndExpand(Component... components)` method to `HorizontalLayout`, `VerticalLayout` where it does:
1) add the given components
2) set the component to 100 % size in the dimension of the layout: height for VL and width for HL
3) set the `flex-grow` to `1` for the components
4) optionally set the height for VL and width for HL to 100 % if **undefined**
(Please pay attention to javadocs to explain what the method does clearly [like in FW 8](https://vaadin.com/api/framework/8.7.0/com/vaadin/ui/VerticalLayout.html#addComponentsAndExpand-com.vaadin.ui.Component...-)
- add Java demos for both of the components with topic `Expanding Content` that can use e.g. some html components with lorem ipsum text that expands, and has e.g. borders to show the size
- add unit tests that verify that the API applies the desired state

As for `FlexLayout` the size would depend on which `flex-direction` is used, I don't see it feasible to add the API there.
